services:
  - type: web
    name: book-management-app
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist/book-management-app
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache
      - path: /*
        name: Content-Type
        value: text/html; charset=utf-8
    routes:
      - type: rewrite
        source: /*
        destination: /index.html