services:
  - type: web
    name: book-management-app
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist/book-management-app/browser
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache
      - path: /*.js
        name: Content-Type
        value: application/javascript
      - path: /*.css
        name: Content-Type
        value: text/css
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    # Add this section to handle MIME types for other common static files
    mimeTypes:
      ttf: font/ttf
      woff: font/woff
      woff2: font/woff2